### ISSUE TITLE
How can I change the CNN into my own model?

### ISSUE THREAD

**Issue by chutongz** [pieterluitjens/DNS_and_INQ#1]
Thanks for providing such a great code.
Now I'm trying to use INQ on my own model, and I'm really new to tensorflow. 
Should I just replace the 'Convolution2D' into my own? What parameters should I set as input of INQLayer?

**Comment by yaysummeriscoming** [comment]
Thanks for having a look :)  Correct, the INQ layer inherits from the Conv2D class, so you can use it as a drop in replacement.  You have 3 parameters to set:

-start epoch
-max value
-bit depth

Max value & bit depth control weight quantisation.  Bit depth controls how many different weights you want to use across the range (-max value, max value), similar to the quantisation used within tensorflow.  I should note that the paper computes an optimal value for max value (section 2.1 of the paper) that I haven't implemented.  I should add that somewhere..

Important note: You also need to add my callback class to your .fit() function.  This callback calls the relevant functions that implement INQ functionality.

Edit: Callback is included in line 138 of the training script

**Comment by chutongz** [comment]
Thanks for relying me!! It makes sense!
My problem is that how could I apply INQ to an existed neutral network like AlexNet etc... Should I modify the 'CreatModel' part?

**Comment by yaysummeriscoming** [comment]
yeah that's right. be aware you'll have to train these models for a few epochs though (paper says 8).  for image net models like alexnet that will take a while
