### ISSUE TITLE
Would you mind shedding some light on the way combining  DNS and INQ together?

### ISSUE THREAD

**Issue by power0341** [pieterluitjens/DNS_and_INQ#2]

**Comment by yaysummeriscoming** [comment]
Sure, you need to do DNS first and then INQ with the DNS mask (T in the code) fixed.  It works pretty well, as DNS prunes all the small weights that would otherwise be quantised to 0.  Keep in mind that INQ must take X% of the remaining non-zero weights, instead of X% of all weights
